#!/usr/bin/env bash

##############################
### XML Parser             ###
###   Compiler Instruction ###
##############################

LANGUAGE=$1

usage() {
    echo " "
    echo "compile"
    echo "  Local compilation script compiles programs within this folder by language selection."
    echo "-------------------------"
    echo "Usage:"
    echo "  $ compile <language_selection>"
    echo "Languages:"
    echo "  * c - Compiles the C (ANSI C99) language version"
    echo "  * d - Compiles the D (current) language version"
    echo " "
}

heading() {
    echo " "
    echo "Setting flags and compiling parser..."
    echo Language Selection: $LANGUAGE
    echo " ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}

compile() {

###=================================###
###     COMPILE FOR C LANG PROGRAM  ###
###         Uses GCC                ###
###=================================###
    if [ "$LANGUAGE" == "c" ]; then
        heading
        echo "   Compiling for C..."
        gcc xml_parser_c.c \
        -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm \
        -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2 \
        -o xml_parser
        echo "   Done!"
        echo " "

###==================================###
###     COMPILER FOR D LANG PROGRAM  ###
###         Uses DMD                 ###
###==================================###
    else
        if [ "$LANGUAGE" == "d" ]; then
            heading
            echo "   Compiling for D..."
            dmd xml_parser_d -O -m64 -ofxml_parser
            echo "   Done!"
            echo " "
        else
            usage
        fi
    fi
    

    return 0
}

compile
